SELECT USER_ID, PRODUCT_ID
  FROM ONLINE_SALE OS
 WHERE EXISTS (
    SELECT 1 
      FROM ONLINE_SALE OS2
     WHERE OS.USER_ID = OS2.USER_ID
       AND OS.PRODUCT_ID = OS2.PRODUCT_ID
       AND OS.ONLINE_SALE_ID != OS2.ONLINE_SALE_ID
 )
 GROUP BY USER_ID, PRODUCT_ID
 ORDER BY USER_ID ASC, PRODUCT_ID DESC;